# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oU-ScG7p0eK2rAY21M7vDC7QMKYhTfId
"""

d={}
def create(key,value,timeout=0):
    if key in d:
        print("error: this key already exists")
    else:
        if(key.isalpha()):
            if len(d)<(1024*1020*1024) and value<=(16*1024*1024): 
                l=[value,timeout]
                if len(key)<=32: 
                    d[key]=l
            else:
                print("error: Memory limit exceeded!! ")
        else:
            print("error: Invalind key_name!! key_name must contain only alphabets and no special characters or numbers")

def read(key):
    if key not in d:
        print("error: given key does not exist in database. Please enter a valid key") 
    else:
        b=d[key]
        stri=str(key)+":"+str(b[0]) 
        print(stri)
            

def delete(key):
    if key not in d:
        print("error: given key does not exist in database. Please enter a valid key") 
    else:
        b=d[key]
        del d[key]
        print("key is successfully deleted")

key = str(input("Enter your key : "))
value = int(input("Enter your value : "))
create(key,value)

key = str(input("Enter your key : "))
read(key)
key = str(input("Enter your key : "))
delete(key)

